spring.application.name=actividad3
server.port=8083

# Conexión a MySQL (Local)
spring.datasource.url=jdbc:mysql://localhost:3306/actividad3_agv
spring.datasource.username=adrian
spring.datasource.password=cocodriloS1

# Configuración de JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true